//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hospital
{
    using System;
    using System.Collections.Generic;
    
    public partial class Randevu
    {
        public string Barkod { get; set; }
        public long HastaTCKN { get; set; }
        public long DoktorTCKN { get; set; }
        public System.DateTime TarihveSaat { get; set; }
        public Nullable<int> ReceteNo { get; set; }
    
        public virtual Doktor Doktor { get; set; }
        public virtual Hasta Hasta { get; set; }
        public virtual Recete Recete { get; set; }
    }
}
